# For reference, see https://aka.ms/yaml

variables:
  M2_LOCAL_REPO: $(Pipeline.Workspace)/local-maven-repo
  MAVEN_OPTS: '-Dmaven.repo.local=$(M2_LOCAL_REPO)'

trigger:
  batch: true

schedules:
- cron: "0 0 * * *"
  displayName: Daily scheduled run
  branches:
    include:
      - develop
    #exclude: 
  always: true
      
jobs:
- job: testframework
  pool: 'ubuntu-20.4-DS1_v2-adopt-adoptium-jdk'
  continueOnError: false
  timeoutInMinutes: 20
  variables:
    SKIP_PUBLICATION: false
  
  workspace:
    clean: all

  steps:

  - task: Cache@2
    inputs:
      key: 'mvn | "$(Agent.OS)" | pom.xml'
      restoreKeys: |
        mvn | "$(Agent.OS)"
        mvn
      path: $(M2_LOCAL_REPO)
    displayName: Configure maven caching

  - task: DownloadSecureFile@1
    name: pgpPrivateKey
    displayName: 'Secrets - download pgp key'
    inputs:
      secureFile: 'order-iom-project-archetype-gpg_private_key_iom.pgp'
    
  - task: MavenAuthenticate@0
    inputs:
      artifactsFeeds: order-iom-snapshots
      mavenServiceConnections: order-iom-sonatype-ossrh
    timeoutInMinutes: 1
    displayName: "Maven authenticate"

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - script: |
      # Only some certain branches are allowed for publication!
      if ! echo "$BUILD_SOURCEBRANCHNAME" | grep -q '^develop$\|^testframework-4\.0$\|^locktest$\|^release-\|^main$'; then
        echo "##vso[task.setvariable variable=SKIP_PUBLICATION;]true"
        echo "##vso[task.logissue type=warning] publication skipped"
      fi
    timeoutInMinutes: 2
    displayName: "Check for publication / release build"
    #enabled: false

  - script: |
      ./mvnw clean verify
    timeoutInMinutes: 10
    displayName: "Build test-framework"
    condition: and(succeeded(), eq(variables.SKIP_PUBLICATION, true))
    env:
      PGP_PASSPHRASE: "literal:$(pgpPassphrase)"
      PGP_SECRETKEY: "keyfile:$(pgpPrivateKey.secureFilePath)"

  - script: |
      ./mvnw clean deploy
    timeoutInMinutes: 10
    displayName: "Publish test-framework"
    #enabled: false
    condition: and(succeeded(), eq(variables.SKIP_PUBLICATION, false))
    env:
      PGP_PASSPHRASE: "literal:$(pgpPassphrase)"
      PGP_SECRETKEY: "keyfile:$(pgpPrivateKey.secureFilePath)"
       
  - task: PublishTestResults@2