/*
 * IOM TRANSMISSION REST API
 * The transmission REST API supports tasks to view and manage transmissions of the IOM.<br>
 *
 * OpenAPI spec version: 1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.intershop.oms.test.businessobject.transmission;

import com.intershop.oms.test.businessobject.OMSBusinessObject;

import lombok.AllArgsConstructor;
/**
 * A transmission id and the process that should be done on this transmission.
 */
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;

@Getter
@Setter
@Accessors(chain = true)
@ToString
@AllArgsConstructor
public class OMSTransmissionUpdate extends OMSBusinessObject
{
    private String id;
    private OMSTransmissionUpdateType updateType;

}
