/*
 * IOM TRANSMISSION REST API
 * The transmission REST API supports tasks to view and manage transmissions of the IOM.<br>
 *
 * OpenAPI spec version: 1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.intershop.oms.test.businessobject.transmission;

/**
 * The type of process to create on a transmission, e.g. to resend a transmission.&lt;br&gt; &lt;br&gt; &#x60;RESEND&#x60; - Resend the transmission.&lt;br&gt; &#x60;CANCEL&#x60; - Cancel the transmission.&lt;br&gt; &#x60;SENT&#x60; - Set the transmission as already sent.&lt;br&gt;
 */
public enum OMSTransmissionUpdateType
{
    RESEND("RESEND"),
    CANCEL("CANCEL"),
    SENT("SENT");

    private String value;

    OMSTransmissionUpdateType(String value)
    {
        this.value = value;
    }

    public String getValue()
    {
        return value;
    }

    @Override
    public String toString()
    {
        return String.valueOf(value);
    }

    public static OMSTransmissionUpdateType fromValue(String text)
    {
        for (OMSTransmissionUpdateType b : OMSTransmissionUpdateType.values())
        {
            if (String.valueOf(b.value).equals(text))
            {
                return b;
            }
        }
        return null;
    }
}
